[phases.setup]
nixPkgs = ["nodejs", "unzip", "rsync"]

[phases.install]
cmds = [
  "npm install",
  "npm install @syncfusion/ej2@^24.2.3",
  "rm -rf /tmp/extracted && mkdir -p /tmp/extracted",
  "unzip -o ./react-base-component.zip -d /tmp/extracted",

  # step 1: copy semua isi react-base-component kecuali folder tambahan
  "rsync -av --exclude='tambahan/' /tmp/extracted/react-base-component/ node_modules/@syncfusion/",

  # step 2: copy isi folder tambahan ke @syncfusion
  "rsync -av /tmp/extracted/react-base-component/tambahan/ node_modules/@syncfusion/"
]

[phases.build]
cmds = [
  "npm run build"
]
